services:
  api:
    image: nest-template
    container_name: nest-template-api
    build:
      context: ../
      target: runner
      dockerfile: .docker/Dockerfile
    ports:
      - "5005:5005"
    env_file:
      - ../.env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/nest_db
    depends_on:
      - db
    volumes:
      - ../logs:/app/logs

  db:
    container_name: nest-template-db
    image: postgres:17-alpine
    # Docker Compose will automatically look for a .env file in the same directory as the docker-compose.yml file
    # and load the environment variables from it
    # env_file: .env
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    # Compose seems not properly read the relative path for the .env file
    ports:
      - "5432:5432"
    # Executing a command to check if the env variables are set
    volumes:
      - postgres_data:/var/lib/postgresql/data # Mounting the volume to persist data

# Top-level volumes use to define named volumes
volumes:
  postgres_data:
