services:
  api:
    container_name: nest-template-api
    build:
      context: ../
      target: runner
      dockerfile: .docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/nest_db
    depends_on:
      - postgres
    volumes:
      - ../logs:/app/logs

  postgres:
    container_name: nest-template-db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
